RAR/RAR/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
   # path('accounts/', include('django.contrib.auth.urls')),
    path( '', include( 'reliable.urls' ), name='home'),
    ]

RAR/reliable/urls.py
from django.urls import path, include
from . import views
app_name = "reliable"
urlpatterns = [
    path('', views.index, name= 'index'),        
    path('pricing/', views.pricing, name= 'pricing'),
    path('register/', views.register, name= 'register'),
    path('logon/', views.logon, name= 'logon'),
    path('logout/', views.logout, name='logout'),
    path('user/', views.user_dashboard, name='user_dashboard'),
    path('service/', views.service, name='service'),
]

RAR/reliable/models.py
from django.db import models
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib.auth.models import User

# Create your models here.
class service_call(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    details = models.TextField(max_length=500)
    datetime = models.DateTimeField(auto_now_add=True)

RAR/reliable/forms.py
from django import forms
from .models import service_call
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, ButtonHolder

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
                user.save()
        return user

class RequestForm(forms.ModelForm):

    class Meta:
        model = service_call
        fields = ( "first_name", "last_name", "phone", "address", "details")

    def __init__(self, *args, **kwargs):
        super(RequestForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
                Field('First Name', id="fname"),
                Field('Last Nam,e', id="lname"),
                Field('Phone Number', id = "phone"),
                Field('Address', id = "address"),
                Field('Describe the problem...', cols="5", id="details"),
                ButtonHolder(
                    Submit('submit', "Submit"),
                    )
                )

RAR/reliable/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from .forms import NewUserForm, RequestForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm
from django.contrib.auth.models import User
from .models import service_call
from datetime import datetime
import os, requests, json
from django.urls import reverse

# Create your views here.
def index(request):
   return render(request, 'reliable/index.html')

def pricing(request):
    return render(request, 'reliable/pricing.html')

def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get('username')
            email=form.cleaned_data.get('email')
            passw=form.cleaned_data.get('password1')
            auser = User.objects.create_user(username = uname, email = email, password = passw)
            login(request, auser)
            message = "Registration successful."
            return render(request, "reliable/index.html", { 'msg' : message })
        message = "Registration unsuccessful, please check your information and try again."
        return render(request, "reliable/register.html", { 'msg' : message })
    form = NewUserForm()
    return render(request=request, template_name="reliable/register.html", context={"register_form":form})

def logon(request):
    if request.method == "POST":
        form = AuthenticationForm(None, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                message = f"You are now logged in as [ {username} ]."
                return render(request, "reliable/index.html", { 'msg' : message })
            else:
                message =  "Invalid username or password."
                return render(request, "reliable/login.html", { 'msg' : message })
        else:
            message =  "Invalid username or password."
            return render(request, "reliable/login.html", { 'msg' : message})
    form = AuthenticationForm()
    return render(request, 'reliable/login.html', {'form': form})

def logout(request):
    auth.logout(request)
    message = "You have successfully logged out."
    return render(request, "reliable/index.html", { 'msg' : message})

def user_dashboard(request):
    return render(request, 'reliable/user.html')

def service(request):
    TILL_URL = os.environ.get("TILL_URL")
    if request.method == "POST":
        form = RequestForm(request.POST)
        if form.is_valid():
            service_call.first_name = form.cleaned_data.get('first_name')
            service_call.last_name = form.cleaned_data.get('last_name')
            service_call.phone = form.cleaned_data.get('phone')
            service_call.address = form.cleaned_data.get('address')
            service_call.details = form.cleaned_data.get('details')
            sc = service_call(first_name = service_call.first_name, last_name = service_call.last_name, phone = service_call.phone, address = service_call.address, details = service_call.details)
            sc.save()
            resp = requests.post(TILL_URL, json={
            "phone": ["14695921148"],
            "method": "SMS",
            "tag" : "alert",
            "text": f'{service_call.phone}: {service_call.first_name} - {service_call.details}',
            })
            message = "A service call has been submitted and a text has been sent to the Technician on duty. We should be contacting you by phone shortly to confirm."
            return render(request, 'reliable/index.html', {'msg' : message })
    form = RequestForm()
    return render(request, 'reliable/service.html', {
        "form": form,
        })

RAR/reliable/templates/reliable/channels.html
https://github.com/pusher/pusher-js

RAR/reliable/templates/reliable/create.html
{% extends 'reliable/layout.html' %}
{% block body %}
{% load crispy_forms_tags %}
{% if message %}
    <div class="w3-center w3-panel w3-xlarge">{{ message }}</div>
{% endif %}
<div class="container" style="padding: 5%">
    <h1 class="w3-jumbo w3-center" style:"text-shadow: 2px 2px 5px #c0c0ff;">Register New User</h1>
    <form method="POST" class="w3-large uniForm">
        {% csrf_token %}
        {{ register_form|crispy }}
        <button class="w3-btn w3-blue" type="submit">Register</button>
    </form>
    <p class="w3-xxlarge w3-center">If you already have an account, click <a href="{% url 'logon' %}">here</a> to login.
</div>
{% endblock %}

RAR/reliable/templates/reliable/index.html
{% extends 'reliable/layout.html' %}
{% block body %}
  <!-- Header/Home -->
  <header class="w3-container w3-padding-32 w3-center w3transparent" id="home">
    <h1 class="w3-jumbo" style="text-shadow: 2px 2px 5px #a0a0ff;">Reliable Air Repair</h1>
    <p class="w3-large">Little Elm, TX   <i class="fa fa-snowflake-o w3-large w3-text-blue"></i>   <a href="tel:4695921148">(469) 592-1148</a></p>
    <hr>
    {% if msg %}
    <p class="w3-xlarge" style="font-family: 'Lucida Console', monospace">{{ msg }}</p>
    <hr>
    {% endif %}
    <p class="w3-xxlarge">"Providing home-owners with a low-cost, professional quality option for residential HVAC services and home appliance repair."</p>
    <img src="https://i.ibb.co/S71cQ1P/Logo.png" alt="logo" class="w3-image" width="992" height="1108">
  </header>
 
{% endblock %}

RAR/reliable/templates/reliable/layout.html
<html>
<head>
<title>Reliable Air Repair</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<script src="https://js.pusher.com/7.0.3/pusher.min.js"></script>
<style>
.mybg {
	background-image: url("https://i.ibb.co/gWfKsjy/mybg.png");
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
	background-color: #fefefe;
}
li {text-indent:5%; list-style-position: inside; border: 1px solid #ddd;}
body, h1,h2,h3,h4,h5,h6 {font-family: "Helvetica", "Arial", sans-serif}
.w3-row-padding img {margin-bottom: 12px}
/* Set the width of the sidebar to 120px */
.w3-sidebar {width: 120px;background: #c0c0c0;}
/* Add a left margin to the "page content" that matches the width of the sidebar (120px) */
#main {margin-left: 120px}
/* Remove margins from "page content" on small screens */
@media only screen and (max-width: 600px) {#main {margin-left: 0}}
</style>
</head>
<body class="w3-white mybg">

<!-- Icon Bar (Sidebar - hidden on small screens) -->
<nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
  <!-- Avatar image in top left corner -->
  <img src="https://i.ibb.co/S71cQ1P/Logo.png" style="width:100%">
  <a href="{% url 'reliable:index' %}" class="w3-bar-item w3-button w3-padding-large w3-white">
    <i class="fa fa-home w3-xxlarge"></i>
    <p>HOME</p>
  </a>
  <a href="{% url 'reliable:pricing' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
    <i class="fa fa-usd w3-xxlarge"></i>
    <p>PRICING</p>
  </a>
  <a href="{% url 'reliable:service' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
    <i class="fa fa-phone w3-xxlarge"></i>
    <p>REQUEST</p>
  </a>
  {% if user.is_authenticated %}
  <a href="{% url 'reliable:user_dashboard' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>{{ user.username }}</p>
  </a>
  {% else %}
  <a href="{% url 'reliable:logon' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-white">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>LOGIN</p>
  </a>
 {% endif %}
</nav>

<!-- Navbar on small screens (Hidden on medium and large screens) -->
<div class="w3-top w3-hide-large w3-hide-medium" id="myNavbar">
  <div class="w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small">
    <a href="{% url 'reliable:index' %}" class="w3-bar-item w3-button" style="width:25% !important">HOME</a>
    <a href="{% url 'reliable:pricing' %}" class="w3-bar-item w3-button" style="width:25% !important">PRICING</a>
    <a href="{% url 'reliable:service' %}" class="w3-bar-item w3-button" style="width:25% !important">REQUEST</a>
    {% if user.is_authenticated %}
    <a href="{% url 'reliable:user_dashboard' %}" class="w3-bar-item w3-button" style="width:25% !important">{{ user.username }}</a>
    {% else %}
    <a href="{% url 'reliable:logon' %}" class="w3-bar-item w3-button" style="width:25% !important">LOGIN</a>
    {% endif %}
  </div>
</div>
<div class="w3-padding-large" id="main">
		{% block body %}
		{% endblock %}
    <!-- Footer -->
  <footer class="w3-content w3-padding-64 w3-text-grey w3-xlarge">
    <a href="https://www.facebook.com/profile.php?id=100074587540902"><i class="fa fa-facebook-official w3-hover-opacity"></i></a>
    <a href="https://www.instagram.com/jsprings482"><i class="fa fa-instagram w3-hover-opacity"></i></a>
    <a href="https://twitter.com/SpringsJeffery"><i class="fa fa-twitter w3-hover-opacity"></i></a>
    <a href="https://www.linkedin.com/in/jeffery-springs-157b4523b/"><i class="fa fa-linkedin w3-hover-opacity"></i></a>
    <br>
    Powered by <a href="https://www.djangoproject.com">Django</a>, <a href="https://www.python.org">Python</a>, <a href="https://www.openSuse.org">openSuse</a>, <a href="www.heroku.com">Heroku</a>, and <a href="https://www.github.com">Git Hub</a>
  <!-- End footer -->
  </footer>

<!-- END PAGE CONTENT -->
</div>

</body>
</html>

RAR/reliable/templates/reliable/login.html
{% extends 'reliable/layout.html' %}
{% block body %}
{% load crispy_forms_tags %}
<div class="container" style="padding: 5%">
    <h1 class="w3-jumbo w3-center" style="text-shadow: 2px 2px 5px #a0a0ff;">Login</h1>
    <p class="w3-xlarge">{{ msg }}</p>
    <form method="POST" class="uniForm" style="font-family: 'Lucida Console', monospace">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="w3-btn w3-blue" type:"submit">Login</button>
    </form>
    <p class="w3-center w3-xxlarge" style="font-family: 'Lucida Console', monospace"> Don't have an account? Create one <a href="{% url 'reliable:register' %}">here</a>.</p>
</div>
{% endblock %}

RAR/reliable/templates/reliable/logout.html
{% extends 'reliable/layout.html' %}
{% block body %}

{% endblock %}

RAR/reliable/templates/reliable/password_reset.html
{% extends 'reliable/layout.html' %}
{% block body %}
{% load crispy_forms_tags %}

<div class="container" style="padding: 5%">
    <h2 class="w3-panel"> Reset Password</h2>
    <hr>
    <p>Forgotten your password? Enter your email address below, and we'll send you instructions for setting a new one.</p>
    <form method = "POST" class="uniForm">
        {% csrf_token %}
        {{ password_reset_form|crispy }}
        <button class="w3-btn w3-blue" type="submit">Send Email</button>
    </form>
</div>

{% endblock %}

RAR/reliable/templates/reliable/password_reset_complete.html
{% extends 'reliable/layout.html' %}
{% block body %}

<div class="container" style="padding:5%">
    <h2 class="w3-panel" style="margin-top: 3%">Password reset complete</h2>
    <hr>
    <p>Your password has been reset. You may go ahead and log in now.</p>
    <a href="{% url 'reliable:logon' %}" class="w3-btn w3-blue">Go to Login page</a>
</div>

{% endblock %}

RAR/reliable/templates/reliable/password_reset_confirmation.html
{% extends 'reliable/layout.html' %}
{% block body %}
{% load crispy_forms_tags %}

<div class="container" style="pagging: 5%">
    <h2 class="w3-panel" style="margin-top:3%">Password Reset Confirmation</h2>
    <hr>
    <p>Please enter your new password.</p>
    <form method = "POST" class="uniForm">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="w3-btn w3-blue" type:"submit">Reset Password</button>
    </form>
</div>

{% endblock %}

RAR/reliable/templates/reliable/password_reset_done.html
{% extends 'reliable/layout.html' %}
{% block body %}

<div class="container" style="padding: 5%">
    <h2 class="w3-panel" style="margin-top:3%">Password reset E-Mail sent.</h2>
    <hr>
    <p>We've emailed you instructionsfor resetting your password, if an account existswith the email you entered. You should receive the email shortly.<br>If you don't receivean email, please make sureyou've entered the address you registered with, and check your spam folder as well.</p>
</div>

{% endblock %}

RAR/reliable/templates/reliable/pricing.html
{% extends 'reliable/layout.html' %}
{% block body %}
<div class="">
<p class="w3-jumbo w3-center" style="text-shadow: 2px 2px 5px #c0c0ff; padding-bottom: 15px;">Pricing Information</p>
<p class="w3-xxxlarge">Central Air Conditioning:</p>
<ul class="w3-xlarge" style="font-family: 'Lucida Console', monospace">
<li>Service Call: <b>$60</b></li>
<li>Preventatice Maintanence: <b>$125</b></li>
<li>Small Part Replacement: <b>$75-150</b></li>
<li>Large Part Replacement: <b>$200-700</b></li>
<li>Outdoor Unit Installation: <b>$750</b></li>
<li>Indoor Unit Installation: <b>$1250</b></li>
<li>Whole System Installation: <b>$1750</b></li>
</ul>
<p class="w3-xxxlarge">Window Unit/Ductless A/C:</p>
<ul class="w3-xlarge" style="font-family: 'Lucida Console', monospace">
<li>Service Call: <b>$40</b></li>
<li>Cleaning: <b>$60</b></li>
<li>Repair: <b>$75</b></i>
<li>Replacement: <b>$100</b></li>
</ul>
<p class="w3-xxxlarge">Central Heating:</p>
<ul class="w3-xlarge" style="font-family: 'Lucida Console', monospace">
<li>Service Call: <b>$75</b></li>
<li>Preventative Maintanence: <b>$125</b></li>
<li>Small Part Replacement: <b>$75-150</b></li>
<li>Large Part Replacement: <b>$200-700</b></li>
<li>Gas Line Service: <b>$250-750</b></li>
<li>Furnace Installation: <b>$1250-2000</b></li>
<li>Electric Heating Installation: <b>$300-1000</b></li>
</ul>
<p class="w3-xxxlarge">Portable Heater/Small Appliance:</p>
<ul class="w3-xlarge" style="font-family: 'Lucida Console', monospace">
<li>Service Call: <b>$40</b></li>
<li>Repair: <b>$50-200</b></li>
<li>Installation: <b>$75-150</b></li>
</ul>
</div>
{% endblock %}

RAR/reliable/templates/reliable/register.html
{% extends 'reliable/layout.html' %}
{% block body %}
{% load crispy_forms_tags %}
<div class="container" style="padding: 5%">
    <h1 class="w3-jumbo w3-center"  style="text-shadow: 2px 2px 5px #a0a0ff;">Register New User</h1>
    <p class="w3-xlarge">{{ msg }}</p>
    <form method="POST" class="w3-large uniForm" style="font-family: 'Lucida Console', monospace">
        {% csrf_token %}
        {{ register_form|crispy }}
        <button class="w3-btn w3-blue" type="submit">Register</button>
    </form>
    <p class="w3-xxlarge w3-center" style="font-family: 'Lucida Console', monospace">If you already have an account, click <a href="{% url 'reliable:logon' %}">here</a> to login.
</div>
{% endblock %}

RAR/reliable/templates/reliable/service.html
{% extends 'reliable/layout.html' %}
{% block body %}
{% load crispy_forms_tags %}

<div class="container" style="padding: 5%">
    <h1 class="w3-jumbo w3-center" style="text-shadow: 2px 2px 5px #a0a0ff;">Request a Service Call</h1>
    <form method="POST" class="w3-large uniForm" style="font-family: 'Lucida Console', monospace">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="w3-btn w3-blue" type="submit">Send!</button>
    </form>
</div>
{% endblock %}

RAR/reliable/templates/reliable/user.html
{% extends 'reliable/layout.html' %}
{% block body %}
<div class="w3-center">
	<p class="w3-jumbo" style="text-shadow: 2px 2px 5px #a0a0ff; padding-bottom:5%">User Information</p>
	<hr>
	<p class="w3-xlarge" style="font-family: 'Lucida Console', monospace">Username: {{ user.username }}</p>
	<p class="w3-xlarge" style="font-family: 'Lucida Console', monospace">Email: {{ user.email }}</p>
	<hr>
	<p class="w3-xxlarge" style="font-family: 'Lucida Console', monospace">Click here to <a href="{% url 'reliable:logout' %}">Logout</a>.</p>
</div>
{% endblock %}